stateDiagram-v2
    [*] --> MESSAGE_RECEIVED : message received
    MESSAGE_RECEIVED --> check_data

    state check_data <<choice>>
    check_data --> REPAIR : data is missing
    check_data --> CREATED : data is valid

    REPAIR --> input_data : data entered via GUI
    
    state input_data <<choice>>
    input_data --> REPAIR : data is missing
    input_data --> CREATED : data is valid
    
    REPAIR --> DELETED : deleted via GUI

    CREATED --> system_check : system generated
    CREATED --> user_check : user authorizes via GUI

    CREATED --> DELETED : deleted via GUI

    state system_check <<choice>>
    system_check --> CREATED : data is missing
    system_check --> AUTHORIZED : data is valid

    state user_check <<choice>>
    user_check --> CREATED : data is missing
    user_check --> AUTHORIZED : data is valid

    AUTHORIZED --> process : authorized

    state process <<choice>>
    process --> have : no processing
    process --> override : processing

    state override <<choice>>
    override --> have : pass rules
    override --> AUTHORIZED : not allowed

    state have <<choice>>
    have --> PROCESSED : has
    have --> allow : does not have

    state allow <<choice>>
    allow --> PROCESSED : allow
    allow --> AUTHORIZED : not allowed

    DELETED --> [*] : complete
    PROCESSED --> [*] : complete
