@startuml
[*] --> MESSAGE_RECEIVED : message received

MESSAGE_RECEIVED --> REPAIR : missing data
MESSAGE_RECEIVED --> CREATED : has data

REPAIR --> CREATED : data entered via GUI
REPAIR --> DELETED : deleted via GUI

CREATED --> AUTHORIZED : system generated
CREATED --> AUTHORIZED : user authorizes via GUI

AUTHORIZED --> AUTHORIZED : business rules fail
AUTHORIZED --> PROCESSED : business rules pass

DELETED --> [*]
PROCESSED --> [*]

@enduml
